### ISSUE TITLE
Displaying my own image instead of a black page.

### ISSUE THREAD

**Issue by greg5678** [jacobsalmela/pi-hole#133]
I have edited the index.html file so that instead of a black page an image pops up. How can instead of a ad and smaller version of the ad appears. Is this possible since pi-hole is an network wide ad blocker. (on  a side note is it safe to port forward port 53?

**Comment by dschaper** [comment]
I'm not sure how this would work performance wise. You'd still have to pull down the full sized ad and that would require a bypass of dnsmasq to allow you to get the full sized source. Once you have the full ad, you'd need some kind of logic to be able to resize on the fly and then re-inject the reduced size ad back into the stream with a source address that is the same as the original ad source. There'd be a lot of spoofing involved and overhead, and trying to guess how to resize the advert. It would be quite the undertaking...

As for port-forwarding, it should be safe (I assume you'd like to be able to access the PiHole from outside of the local network? There are a few examples of cloud based PiHole implementations on the front page that basically do that, but instead of serving from the Pi they are serving from a VPS.)

**Comment by jacobsalmela** [comment]
@greg5678 so are you saying you want to see the ad, just in a smaller size?  I don't quite understand the question.

A safer way would be to use a VPN, but I understand why you want to do it.  I never underestimate the capabilities of malevolents, so any entry into your network is an avenue of attack.  I guess it's really just how comfortable you are with it.  You might also run into some annoyances if you don't have a static address at home, so when your lease from your ISP expires, you would have to edit your DNS servers again.

**Comment by greg5678** [comment]
I would like to replace the ads on websites with my own images.

**Comment by jacobsalmela** [comment]
You can replace the ads with whatever you want by [editing the index.html file](http://pi-hole.net/faq/is-it-possible-to-change-the-blank-page-that-takes-place-of-the-ads-to-something-else/).
