### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#134]
Many ads come through via https.  `lighttpd` supports it we just need to figure it out.

**Comment by dschaper** [comment]
If anyone has some example domains to test with or some webpages, if you could please post them so we have something to use for testing purposes. Thanks!

**Comment by przemasisko** [comment]
For example, there is a problem domain https://c.allegrostatic.pl (https://c.allegrostatic.pl/images/velalayout/8a7cb973.icon.png).

Domain blocking works by: /usr/local/bin/whitelist.sh c.allegrostatic.pl, but don't work Apply Everytime by file whitelist.txt. Strange thing.

**Comment by jacobsalmela** [comment]
https://www.flashback.org/

Seems to be a good site to test things out on.  I have a lot of trouble blocking ads there.

**Comment by dschaper** [comment]
flashback.org is going to be an interesting one. They self host all the ads, so trying to find the right block recipe that doesn't block content...

**Comment by chriskacerguis** [comment]
@jacobsalmela what are the challenges you are facing with https?

**Comment by dschaper** [comment]
Flashback.org can't be blocked without severe site breakage. They host all their own ads on their own servers, so there really isn't a way to block them. 

@przemasisko I can't access allergrostatic.pl, I'm getting a Connection Refused error.

**Comment by dschaper** [comment]
@chriskacerguis I think HTTPS is taken care of, the protocol doesn't (shouldn't) matter, https/ftp/ssh/whatever since the actual A records are getting blocked, so there is no communication with the server in any case, but what appears to be HTTPS issues are actually IPv6 AAAA records getting through. At least that's how it appears now. I can block https://amazon.com with no problem, as they don't have AAAA records set up, but https://google.com is an issue, as noted in another thread, the A record is blocked, but the domain still appears because there is an AAAA record that is getting through.

**Comment by jacobsalmela** [comment]
Same error here for allergrostatic.pl.

@dschaper you are probably right.  I have also been watching the log file for some sites and they will query both IPv4 and IPv6--the A record gets blocked properly, but the AAAA records resolve to the real ad site.  I think I need to close this and make a IPv6 milestone instead.

**Comment by c-hoeger** [comment]
I am also experiencing extreme slow (up to more then 60 seconds!!!) page loading whenever I use Safari on macOS or iOS while Firefox is doing quite well. After examining the requests with the Safari developer tools, I found out, that many requests to ad sites use https, e.g. see this cURL:

```
$ curl 'https://script.ioam.de/iam.js' -XGET -H 'DNT: 1' -H 'Referer: http://www.spiegel.de/' -H 'Accept: */*' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12'
curl: (7) Failed to connect to script.ioam.de port 443: Operation timed out
```

while when I use http instead of https:

```
$ curl 'http://script.ioam.de/iam.js' -XGET -H 'DNT: 1' -H 'Referer: http://www.spiegel.de/' -H 'Accept: */*' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12'
var x = "Pi-hole: A black hole for Internet advertisements."
```

As you can see, these requests time out because the raspi is not answering.

I solved that in adding this https configuration file:

```
# cat /etc/lighttpd/external.conf
$SERVER["socket"] == ":443" {
  ssl.engine = "enable"
  ssl.pemfile = "/etc/lighttpd/certs/lighttpd.pem"
}
```

generating self-signed cert:

```
mkdir /etc/lighttpd/certs
cd /etc/lighttpd/certs
openssl req -new -x509 -keyout lighttpd.pem -out lighttpd.pem -days 365 -nodes
chmod 400 lighttpd.pem
```

and restart lighttpd.

Now the only problem is, that the certificate does not match the certificate of the website it is accessing and thus, Safari will open a window where one has to confirm the self-signed certificate.
But then, all Safari browsers in my network behave as fast as before.

I am wondering whether it would be somehow possible to reject ipv6 connections to port 443 on the pi instead of dropping them silently. Unfortunately I have no clue about ipv6 and thus wasn't yet able to create such a rule.

**Comment by DL6ER** [comment]
Why should we do this with IPv6 only?

**Comment by c-hoeger** [comment]
It appeared to be an ipv6 routing problem inside my own network. After I disabled ipv6 completely, the problem is gone.
