### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by mmontminy** [jacobsalmela/pi-hole#147]
I believe there's a bug/design flaw with gravity.sh preventing it from properly handling whitelist.txt. Either the pattern matching and grep options are incorrect, or it's processing the wrong files.

As it is now, whiltelist entries are converted to a regex pattern that's line anchored with ^ and $. Additionally, the grep command is also told to only match exact lines using -x. That's fine, however the file being grepped, pihole.0.matter.txt, has entries in a hosts files format, rather than domain per line. As such, the patterns never match.

It seems to me that using this more exact pattern matching, the whitelist processing has to happen after the hosts to domain processing does, and happen on the pihole.3.supernova.txt file instead. Either that, or the pattern matching needs to be relaxed and not anchored to the start/end of lines.

I've updated my gravity.sh to remove the ^$ as well as -x, and it's working. I suspect a side effect of this quick fix is going to be whitelisting additional domains.

**Comment by jacobsalmela** [comment]
I agree, it doens't work as well as it should.  The latest commit to `whitelist.sh` seems to work every time.  I think I will outsource the work to that script instead of having it built inside `gravity.sh`.

**Comment by jacobsalmela** [comment]
I'm thinking this will work:

```
  # Outsource the whitelisting of domains using the whitelist.sh script
  if [[ -r $whitelist ]];then
    # Create a variable to contain each domain delimited by a space, which is what the whitelist.sh script expects
    latentWhitelist=$(cat $whitelist)
    whitelist.sh $latentWhitelist
  else
    echo "** User-defined whitelist is empty."
  fi
```

**Comment by jacobsalmela** [comment]
The above code works, but `whitelist.sh` does not remove IPv6 entries, so the domain could still potentially be blocked.

**Comment by PromoFaux** [comment]
@jacobsalmela I had a bit of a brainwave earlier... and MAY have fixed gravity.sh's handling of whitelists.

The code needs tidying up as I've just hacked it in as a proof of concept

basically changes the workflow so that the white/blacklisting is not done until the penultimate step, at which point I'm using a perl one-liner to remove anything from the gravity.list file that matches any of the domains in the latentwhitelist.txt

please see https://github.com/PromoFaux/pi-hole/commit/f5b5e12bc29dde2513b0647c5093ded73a5fb150 for details.

Let me know if you can see this breaking anything else.. But I will tidy it up and submit a pull later if you're happy?

**Comment by jacobsalmela** [comment]
fixed by #174

**Comment by my-ix** [comment]
I whitelist booking.com but it seems not working, as I am still not able to browse to the site.

**Comment by dschaper** [comment]
Open an issue at https://discourse.pi-hole.net as this thread was closed over three years ago.
