### ISSUE TITLE
Provide a command to update to latest version

### ISSUE THREAD

**Issue by baschwartz** [jacobsalmela/pi-hole#175]
It would be nice to have a command to update Pi-Hole and the domain lists. Thanks

**Comment by dschaper** [comment]
Thanks, we're working on building the Pi-Hole into a Debian package that would be available via `apt-get` or `aptitude` or your favorite package manager. For now, you can always run `curl -L install.pi-hole.net | bash` and you will get the latest released version.

**Comment by jacobsalmela** [comment]
Yeah, this is basically the same as #98.  You can also run `gravity.sh` to update the lists at anytime.

The problem I'm running into now is time to fix all the issues.  @dschaper has been a life-saver fielding questions and.

I close this since it is a duplicate, but thanks for letting us know your wants.
