### ISSUE TITLE
adblock.mahakala.is has some issues

### ISSUE THREAD

**Issue by kurumushi** [jacobsalmela/pi-hole#35]
This hosts file blocks many legitimate sites, including both the download site for adobe flash and rival adblock lists (it blocks hosts-file.net which is one of your pihole sources.) It also includes lines at the top that give domain names to the hosts 'debian,' and 'android,' which may not be wanted by some people.

**Comment by jacobsalmela** [comment]
The mahakala list has caused some other problems, too, but it definitely helps more than it hinders.  I show these entries at the top of my list:
```
localhost
localhost.localdomain
android
android.localhost
test
test.localhost
debian
debian.localhost
```
I agree these are probably not the best entries to include by default.  You could easily add these to `/etc/pihole/whitelist.txt` but not everyone will do that.

I will look into a way to remove these entries from this, or any list.

**Comment by rmceoin** [comment]
In what situation would a single bare word be appropriate to blacklist?  Unless we want to block an entire TLD.  But do any of the downloaded lists contain a TLD?  If not, then I'd say skip any line where the host specified is a single word without a period.   

For the rest perhaps a regex to strip lines with *.localdomain and *.localhost

**Comment by jacobsalmela** [comment]
I'm not sure `grep` will interpret the `*`.  Currently, we are using `awk` to append a `$` to the end of each line. I have always struggled with regex, but I agree with your logic.  Any one word lines probably isn't a domain. 

We might be able to add all of those entries at the beginning of the user's `whitelist.txt` the [way I used to do it](https://github.com/jacobsalmela/pi-hole/blob/f6ccb4b658ec67971472965491b728abdcfcc060/gravity.sh#L105-L108) for the hosts file.  But I think some sort of regex/data validation would be better than hardcoding stuff.

**Comment by kurumushi** [comment]
This command will delete all domains that do not contain a dot.
```
sed -e '/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\} .*\..*$/!d'
```

**Comment by jacobsalmela** [comment]
Awesome!  `sed` experts are the best.  Would you mind explaining how each section of the command works?

**Comment by korhadris** [comment]
Hopefully I'm not stealing your thunder, or being overly descriptive below...

"/": sed delimiter
"^": beginning of line
"[0-9]\{1,3\}": any 1 to 3 digit number
"\.": a single '.' character
These are repeated 4 and 3 times to match an IPv4 address.
" ": a single space
".*\..*": anything.anything (anything could include other '.' characters too), so it'll match every name that at least has one '.'  in it.
"$": end of line, if you want to match a '$' character, you should use "\$"
"/": sed delimiter
"!d": delete non matches

All that said, you could use "grep -e" to match the lines you are looking for as well. With the same regexp (possibly modified for $ matching if that's what you are looking for).

If it is a single word you are looking to remove you could also try something like "grep -ve '^[0-9.]\+ \+\w\+$'"

Additional regexp explanations:
"[0-9.]\+": match one or more ("\+" part) numbers or '.' characters
" \+": match one or more spaces (I don't know if you existing formatting only creates a single space, then you could skip the \+ part)
"\w\+": one or more "word" characters (letters and numbers)
"$": end of line, important in my example in particular, since this is looking for single names to match and not print,  versus original regexp that looks for dotted names to match and not delete.

**Comment by kurumushi** [comment]
No need to worry about my thunder, I think you explained it nicely.

**Comment by gomoku** [comment]
I agree that mahakala list breaks some legal websites, as for me I've noticed it breaks many legal porn tubes, as well one popular regular website: www.playok.com. Another thing that is strange is that there is no contact to mahakala author as mahakala list has no either support site like an issues tracker or a forum, nor any contact info in the list, like commented introduction section at the beginning of the list file, like for example in EasyList:
```

! Homepage: https://easylist.to/ ! Licence: https://easylist.to/pages/licence.html ! 
! Please report any unblocked adverts or problems
! in the forums (https://forums.lanik.us/)
! or via e-mail (easylist.subscription@gmail.com). 
! GitHub issues: https://github.com/easylist/easylist/issues 
! GitHub pull requests: https://github.com/easylist/easylist/pulls 
```
And the only two links which lead to mahakala I've found in Google are:
https://mahakala.is/ - here is nothing but a logo of meditating Mahakala god like Budda
https://adblock.mahakala.is - the list's hosts file

As seen mahakala breaks so many legitimate websites, and there is no contact /bug tracker/ forum to send the broken websites to be fixed.

**Comment by WaLLy3K** [comment]
If you want to contact the Mahakala list maintainer, grab the gmail address that's listed when you whois the domain. The maintainer is very responsive to false positive queries :)

**Comment by gomoku** [comment]
Thanks, I've missed that  :) However, you agree that it is a little hidden, and better would be to have more public contact like an issues tracker or a forum.

**Comment by mahakala** [comment]
hi guys,

i'm the hoster of this file on mahakala.is

for issues look at https://forum.xda-developers.com/showthread.php?t=1916098 - thats the origin of the file.

i could fork it do the requested changes discussed here - but to be honest, i'd like to keep my work as simple as possible. 

best,
thomas

**Comment by gomoku** [comment]
From https://forum.xda-developers.com/showthread.php?t=1916098:

> because of the extreme blocking nature.

Oh. Hey, I just would like to know why ||hosts-file.net^ and ||playok.com^ have been blocked?

**Comment by dschaper** [comment]
@mahakala Thanks for posting here with us!
