### ISSUE TITLE
ads getting through piblocker & blacklist..

### ISSUE THREAD

**Issue by Symbiot78** [jacobsalmela/pi-hole#44]
![2015-09-15_10-58-20](https://cloud.githubusercontent.com/assets/3314249/9872382/592bb13e-5b99-11e5-9b6b-04cf0ae4e05c.png)

As screenshot shows site is added to blacklist, ping is adblock but ads are still getting through... 

Browser i MS Edge. 

I've cleared EVERYTHING in edge... any ideas or things that would be worth testing?

**Comment by Symbiot78** [comment]
![2015-09-15_11-13-27](https://cloud.githubusercontent.com/assets/3314249/9872626/d85dab6e-5b9a-11e5-8dcb-58e2bd02d254.png)

this is the source from the site..

**Comment by korhadris** [comment]
The image displayed is hosted on glocdn.investing.com not on pubads.g.doubleclick.net (which is where the link directs you two if you follow it).

**Comment by poblabs** [comment]
I just ran `cat /etc/pihole/gravity.list | grep investing.com` and didn't find investing.com as part of a black holed domain. This would explain why you're seeing the image as @korhadris mentioned. If you click on it though, it should be blocked. 

```
pi@dns ~ $ cat /etc/pihole/gravity.list | grep pubads.g.doubleclick.net
192.168.0.3 pubads.g.doubleclick.net
192.168.0.3 securepubads.g.doubleclick.net
```

**Comment by Symbiot78** [comment]
Yeah that was my thought as well.. But how does an addin like Adblock know to block the same ad?
Doesn't it use the same tech?

**Comment by Symbiot78** [comment]
I see they use css injecting as well.. 
I guess I'm just looking for the whole package

**Comment by poblabs** [comment]
Yeah adblock looks for certain advertisements using the `<div>` on the page and blocks it that way. The ads are still loaded, but adblock hides it.

Pi-hole blocks the ad from even loading (by using DNS) - but if the ad is on a trusted server (like investing.com), then there's not much you could do.

**Comment by jacobsalmela** [comment]
@poblabs said it well.  The Pi-hole cuts ads off at the source for an entire domain or subdomain, where as ABP uses CSS-injection.  Each has their own strengths/weaknesses.  As is true of many things in technology, a layered approach usually works best.  Personally, I use the Pi-hole for blocking the majority of ads and saving bandwidth, and then I supplement it with ABP for cases like this.

Since it's not really an issue with the functionality of the Pi-hole itself, rather the specific site/ad combo, I will close this issue.
