### ISSUE TITLE
Problem with javascript in some websites

### ISSUE THREAD

**Issue by fipm** [jacobsalmela/pi-hole#59]
Hi,

I noticed that with pi-hole as my primary dns enable, I can't interact with javascript menus and links in various websites. If I temporarily change my dns settings and visit the website, everything goes back to normal. Here is a universally accessible website as an example:
http://www.scholl.co.uk/home/foot-care/insoles-and-arch-supports/
If I visit the website with pi-hole enabled, the button at the top acknowledging the use of cookies cannot be clicked, and all the menus in the page link to # 
I tried to whitelist the websites, but it does not help. Any suggestions?

**Comment by DonLexos** [comment]
I would say try it when you remove the mahakala list from the sources. It is known to break normal sites.

**Comment by jacobsalmela** [comment]
Yes, the mahakala list definitely has been giving users more trouble than it's worth.  If you want to enable it and the site in question still isn't loading the scripts, you will want to figure out what domain(s) they may be trying to get loaded from.

I suggest reading this article, which explains how you may need to whitelist other domains than just the site you want to whitelist, due to how DNS spoofing works.

http://pi-hole.net/whitelist-or-blacklist-a-website/

**Comment by fipm** [comment]
Thanks. Disabling the mahakala list seems indeed to have solved the problem. I will read more about dns spoofing to see if I can pinpoint the culprit.

**Comment by jacobsalmela** [comment]
For the Scholl's Website, I found these domains:

```
www.google.com
ssl.gstatic.com
lh5.googleusercontent.com
www.gstatic.com
apis.google.com
plus.google.com
www.scholl.co.uk
www.google-analytics.com
maps.googleapis.com
csi.gstatic.com
aax-eu.amazon-adsystem.com
js-agent.newrelic.com
bam.nr-data.net
```
