### ISSUE TITLE
DHCP server?

### ISSUE THREAD

**Issue by richardthombs** [jacobsalmela/pi-hole#80]
I'm thinking it would be a good idea for the Pi-Hole to include a DHCP server so that it can give machines the correct DNS settings when they connect to the network.

I'll happily hack about with this if you think it's a good idea.

Cheers,

R.

**Comment by meliton** [comment]
My experience with Pi's in general is that the more services you run on them, the less responsive they become.

**Comment by jacobsalmela** [comment]
It would probably work, but you would also probably need to set it up as a router, which *would* be a lot more demanding.  As it is, the Pi-hole just handles DNS queries and serves tiny Webpages in place of ads, so I do not plan to do this.  Thank you though!

**Comment by DonLexos** [comment]
Easiest for your LAN clients is to simply set your Pi as first DNS in your router, and Google's (or another) as second as a fallback if it fails for some reason. All clients will get the PiHole as first DNS. Far easier than setting it up manually in Android for example manually.
Adding a full DHCP and Router might be overkill for this project, especially since that will bypass any settings you already have in your router.

**Comment by richardthombs** [comment]
Thank you :)

**Comment by jacobsalmela** [comment]
Yup, the router setting is best.  I have thought of making an FAQ for that, but there are so many different routers...
